
server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_registro
    username: root
    password: mysql
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: MYSQL
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    